# Generated by Django 5.2.8 on 2025-12-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone_number', models.CharField(max_length=15)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_method', models.CharField(choices=[('mpesa', 'M-PESA'), ('credit_or_debit_card', 'Credit/Debit Card')], default='mpesa', max_length=30)),
                ('transaction_status', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('transaction_code', models.CharField(max_length=100, unique=True)),
                ('transaction_reference_number', models.CharField(max_length=100, unique=True)),
                ('transaction_result_description', models.TextField(blank=True, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
