# Generated by Django 5.2.8 on 2025-12-01 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_transactions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
